apiVersion: v1
kind: Service
metadata:
  name: cats-node
  labels:
    application: cats-app
    component: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30000
  selector:
    name: cats-pod
    