---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cats
  namespace: cats-ns
  labels:
    course: clo835
    week: assgn2
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cats-pod
  template:
    metadata:
      labels:
        name: cats-pod
    spec:
      containers:
      - name: cats
        image: 045278979811.dkr.ecr.us-east-1.amazonaws.com/clo835-assgn2:catsv0.1
        # httpd:2.4-alpine