apiVersion: v1
kind: Service
metadata:
  name: dogs-node
  labels:
    application: dogs
    component: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
  selector:
    name: dogs-pod
    